version: '3.7'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: nodejs
    ports:
      - "3308:3306"
    volumes:
      # Mysql
      - db:/var/lib/mysql
    networks:
      - backend

  web:
    depends_on:
      - mysql
    build: ./
    ports:
      - "3006:3000"
    volumes:
      - ./:/app
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - backend

  adminer:
    build:
      context: ./adminer
      args:
        - INSTALL_MSSQL=false
    environment:
      - ADMINER_PLUGINS=
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  db:

networks:
  backend: